const keyValues = 
  {numbers: [
    {id: "one",
    value: 1},
    {id: "two",
    value: 2},
    {id: "three",
    value: 3},
    {id: "four",
    value: 4},
    {id: "five",
    value: 5},
    {id: "six",
    value: 6},
    {id: "seven",
    value: 7},
    {id: "eight",
    value: 8},
    {id: "nine",
    value: 9},
    {id: "zero",
    value: 0}
  ],
   operators: [     
     {id: "add",
    value: "+"},
     {id: "subtract",
    value: "-"},
     {id: "multiply",
    value: "*"},
     {id: "divide",
    value: "/"},
   ],
   equals:{id: "equals",
         value: "="},
   decimal:{id: "decimal",
         value: "."},
   clear:{id: "clear",
         value: "C"}  
  }
 export {keyValues};